modLoader="javafml"
loaderVersion="[52,)"
license="GPL-3.0"

[[mods]]
modId="chaoschickens"
version="${version}"
displayName="Chaos Chickens"
description='''
Chickens with chaotic traits! Every chicken that spawns has a random chaos trait —
making them unpredictable, hilarious, and sometimes deadly. Explosive, speedy,
golden, teleporting, and more!
'''
authors="DemonZ Development, Cyrus"
logoFile="icon.png"

[[dependencies.chaoschickens]]
modId="forge"
mandatory=true
versionRange="[52,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaoschickens]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
