# Fabric Mod Properties
# Supports Minecraft 1.20.4 - 1.21.1+
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.0
# + denotes compatibility range
fabric_version=0.102.0+1.21.1

# Mod Properties
mod_version=1.1.3
maven_group=com.chaoschickens
archives_base_name=chaoschickens-fabric

# Java
java_version=17
